FROM node:14.20-alpine

WORKDIR /app

COPY ./types ./types

COPY ["./server/package.json", "./server/yarn.lock", "./server/"]
RUN cd server && yarn install && yarn add link:../types && cd ..
COPY ./server ./server

EXPOSE 8080

CMD ["yarn", "--cwd", "server", "start"]